/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HowToPlayRouteImport } from './routes/how-to-play'
import { Route as JoinRouteImport } from './routes/join'
import { Route as NewRouteImport } from './routes/new'
import { Route as TCodeRouteImport } from './routes/t.$code'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HowToPlayRoute = HowToPlayRouteImport.update({
  id: '/how-to-play',
  path: '/how-to-play',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const TCodeRoute = TCodeRouteImport.update({
  id: '/t/$code',
  path: '/t/$code',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/how-to-play': typeof HowToPlayRoute
  '/join': typeof JoinRoute
  '/new': typeof NewRoute
  '/t/$code': typeof TCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/how-to-play': typeof HowToPlayRoute
  '/join': typeof JoinRoute
  '/new': typeof NewRoute
  '/t/$code': typeof TCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/how-to-play': typeof HowToPlayRoute
  '/join': typeof JoinRoute
  '/new': typeof NewRoute
  '/t/$code': typeof TCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/how-to-play' | '/join' | '/new' | '/t/$code'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/how-to-play' | '/join' | '/new' | '/t/$code'
  id: '__root__' | '/' | '/how-to-play' | '/join' | '/new' | '/t/$code'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HowToPlayRoute: typeof HowToPlayRoute
  JoinRoute: typeof JoinRoute
  NewRoute: typeof NewRoute
  TCodeRoute: typeof TCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-to-play': {
      id: '/how-to-play'
      path: '/how-to-play'
      fullPath: '/how-to-play'
      preLoaderRoute: typeof HowToPlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t/$code': {
      id: '/t/$code'
      path: '/t/$code'
      fullPath: '/t/$code'
      preLoaderRoute: typeof TCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HowToPlayRoute: HowToPlayRoute,
  JoinRoute: JoinRoute,
  NewRoute: NewRoute,
  TCodeRoute: TCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
